Optional image writing to additional sheets
eastgenomics/eggd_generate_variant_workbook pull request #116
Opened 2022-08-08 12:32 UTC by jethror1

## Summary

Adds ability to pass in images to write to extra sheets in the workbook (i.e. graphs), can control sheet naming and image sizes with additional arguments `-iimage_sheet_names` and `-iimage_sizes` respectively.

If size not specified, will default to maximum of 90% of 1920*1080, retaining original image aspect ratio to fit nicely on standard 1080p monitors.

## New functions

- `generate_workbook.verify_images`: assertions to check validity of given image related arguments
- `excel.write_images`: controls writing of images to new sheets

## Example jobs and outputs

- single image: https://platform.dnanexus.com/projects/GFFvFG042Zj7FxK74bpKVbjV/monitor/job/GFjPG2042Zj84x6ZG3gqBxBv

![image](https://user-images.githubusercontent.com/45037268/183411112-0b7c8896-7743-47ce-80d5-ed570ef8b5cc.png)

- single image w/ name and size specified (`-iimage_sheet_names="thisIsFine" -iimage_sizes="960:540"`): https://platform.dnanexus.com/projects/GFFvFG042Zj7FxK74bpKVbjV/monitor/job/GFjP8B042Zj78bZBGgJJ8XFp

![image](https://user-images.githubusercontent.com/45037268/183410873-8e3130bb-53f4-4da4-84c0-cf0611fe6be3.png)

- two images: https://platform.dnanexus.com/projects/GFFvFG042Zj7FxK74bpKVbjV/monitor/job/GFjPJ6042ZjJG8p1GBpvFGbV

![image](https://user-images.githubusercontent.com/45037268/183411893-99651032-ac68-4328-a098-764c94414a52.png)

![image](https://user-images.githubusercontent.com/45037268/183411988-948f3f53-40bf-4d78-b218-0da1c8276be3.png)

- two images w/ names and sizes specified (`-iimage_sheet_names="thisIsFine aNiceGraph" -iimage_sizes="960:540 1440:810"`): https://platform.dnanexus.com/projects/GFFvFG042Zj7FxK74bpKVbjV/monitor/job/GFjPK3Q42Zj711yx90y9Zx8B
![image](https://user-images.githubusercontent.com/45037268/183411632-283ca3f4-94c2-422b-9307-56538a015d44.png)

![image](https://user-images.githubusercontent.com/45037268/183411701-1e00cb32-5005-4382-93df-27e39c845c42.png)

## Unit tests

```
$ python3 -m pytest resources/home/dnanexus/generate_workbook/tests/
==================================== test session starts =====================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/jethro/Projects/eggd_vcf2xls_nirvana/resources/home/dnanexus/generate_workbook/tests, configfile: pytest.ini
collected 35 items                                                                                                                               

resources/home/dnanexus/generate_workbook/tests/test_columns.py ...........                                                                [ 31%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py .......                                                                    [ 51%]
resources/home/dnanexus/generate_workbook/tests/test_utils.py ........                                                                     [ 74%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py .........                                                                      [100%]

============================================================== 35 passed in 28.34s ===============================================================
```

2022-08-08 12:32 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`resources/home/dnanexus/generate_workbook/utils/excel.py`](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/fd77901ccb688fcc0114b3292bc919e03e3c128a/resources/home/dnanexus/generate_workbook/utils/excel.py):

> [Line 509:5](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/fd77901ccb688fcc0114b3292bc919e03e3c128a/resources/home/dnanexus/generate_workbook/utils/excel.py#L509): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2022-08-08 13:02 UTC, kjwinfield approved these changes

2022-08-08 14:17 UTC, mattgarner requested changes
> Reviewed 1 of 4 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116)* status: all files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 37 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xillT3J8h4B-lf5v9:-N8xillUC2KaldmrFLyO:b-beduzg) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/dxapp.json#L37)):*
> ```JSON
>       "class": "array:file",
>       "optional": true,
>       "help": "Images to write to separate sheets. Sheet names may be specified with --image_sheet_names."
> ```

Any restrictions on image file types?



_Code quote:_
```JSON
Images to write to separate sheets. Sheet names may be specified with --image_sheet_names
```
___
*[`dxapp.json` line 44 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xiysL4-esubx_wybQ:-N8xiysL4-esubx_wybR:bxqg9h8) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/dxapp.json#L44)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "'Names to use for image sheets, these MUST be the same number as the number of images passed and in the same order. If not given, this will default image1, image2...",
> ```

Could you describe the usage when multiple names are passed?
e.g. is it:
`-iimage_sheet_names="image1,image2"` ?

I see this is described in the readme, might be helpful to include it here too



_Code quote:_
```JSON
Names to use for image sheets, these MUST be the same number as the number of images passed and in the same order.
```
___
*[`dxapp.json` line 52 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xjPK-Ctib9dVV2Iuh:-N8xjPK-Ctib9dVV2Iui:b5n7q5j) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/dxapp.json#L52)):*
> ```JSON
>       "class": "string",
>       "optional": true,
>       "help": "Sizes to set for images passed with --images, formatted as colon separated width:height in px, these MUST be same number as the number of images passed and in same order.",
> ```

Multiple usage details?



_Code quote:_
```JSON
Sizes to set for images passed with --images, formatted as colon separated width:height in px, these MUST be same number as the number of images passed and in same order.
```
___
*[`src/code.sh` line 72 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xlo5x-FOQJC7mNyKF:-N8xlo5x-FOQJC7mNyKG:bokhaoh) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/src/code.sh#L72)):*
> ```Shell
>     args=""
>     if [ "$additional_files" ]; then args+="--additional_files $(find ~/in/additional_files -type f -name "*") "; fi
>     if [ "$images" ]; then args+="--images $(find ~/in/images -type f -name "*") "; fi
> ```

Is this always going to maintain the order in which they were passed into the app?

If I pass in 3 images in this order:
B.png
A.png
C.png

with 3 names:
1
2
3

Then I expect
B.png -> 1 
A.png -> 2
C.png -> 3


Do we actually end up with:
C.png -> 1 
B.png -> 2
A.png -> 3

since find `~/in/images -type f -name "*"` gives:
 ```
./C.png
./B.png
./A.png
```



_Code quote:_
```Shell
find ~/in/images -type f -name "*"
```


<!-- Sent from Reviewable.io -->

2022-08-08 16:18 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 37 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xillT3J8h4B-lf5v9:-N8yCueF7WmwVVV_zHtg:bri0w0o) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/dxapp.json#L37)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Any restrictions on image file types?
</blockquote></details>

this uses `filetype.is_image()` to check if it is a valid image type here: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/2c54eeb98097baf44451e9694f258c92caba98e6/resources/home/dnanexus/generate_workbook/generate_workbook.py#L364

these are the types that filetype module recognises as an image: https://pypi.org/project/filetype/#supported-types

and openpyxl uses Pillow to read images, these are the ones it supports: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html
___
*[`dxapp.json` line 44 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xiysL4-esubx_wybQ:-N8yCSzU8knmjm_ByspZ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/dxapp.json#L44)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could you describe the usage when multiple names are passed?
e.g. is it:
`-iimage_sheet_names="image1,image2"` ?

I see this is described in the readme, might be helpful to include it here too
</blockquote></details>

Done.
___
*[`dxapp.json` line 52 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xjPK-Ctib9dVV2Iuh:-N8yBq-_5RVGWBW-AcAE:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/dxapp.json#L52)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Multiple usage details?
</blockquote></details>

Done.
___
*[`src/code.sh` line 72 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xlo5x-FOQJC7mNyKF:-N8y9a1QC10XI2ULnNb1:b-djqyvt) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/src/code.sh#L72)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this always going to maintain the order in which they were passed into the app?

If I pass in 3 images in this order:
B.png
A.png
C.png

with 3 names:
1
2
3

Then I expect
B.png -> 1 
A.png -> 2
C.png -> 3


Do we actually end up with:
C.png -> 1 
B.png -> 2
A.png -> 3

since find `~/in/images -type f -name "*"` gives:
 ```
./C.png
./B.png
./A.png
```
</blockquote></details>

hmmm so I wrote this to mimic the structure in app for array inputs and it looks like it doesn't sort by path by default (reading the docs I think it defaults to sorting by modified time on the files):
```
$ tree
.
└── in
    └── images
        ├── 0
        │   └── C.png
        ├── 1
        │   └── A.png
        ├── 2
        │   └── D.png
        └── 3
            └── B.png

$ images=$(find ./in/images/ -type f -name "*")
$ echo $images
./in/images/3/B.png ./in/images/0/C.png ./in/images/2/D.png ./in/images/1/A.png
```

if we pipe through `sort` life is good since DNAnexus has the incrementing integer in the path:
```
$ images=$(find ./in/images/ -type f -name "*" | sort)
$ echo $images
./in/images/0/C.png ./in/images/1/A.png ./in/images/2/D.png ./in/images/3/B.png
```

but in the job it sorts as we expect: https://platform.dnanexus.com/projects/GFFvFG042Zj7FxK74bpKVbjV/monitor/job/GFjY32842ZjPVQPG48zY6Jgq

rebuilt adding pipe through `sort` which is also in the order we expect and feels more robust and is correctly ordered: https://platform.dnanexus.com/projects/GFFvFG042Zj7FxK74bpKVbjV/monitor/job/GFjY9Bj42Zj7yj084XK1jgXk 


this was a good catch though, 10/10 reviewing :smile: 


<!-- Sent from Reviewable.io -->

2022-08-09 09:17 UTC, mattgarner approved these changes
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

___
*[`dxapp.json` line 37 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xillT3J8h4B-lf5v9:-N90sX3u3jHELHH9u6cj:beyexlz) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/dxapp.json#L37)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this uses `filetype.is_image()` to check if it is a valid image type here: https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/2c54eeb98097baf44451e9694f258c92caba98e6/resources/home/dnanexus/generate_workbook/generate_workbook.py#L364

these are the types that filetype module recognises as an image: https://pypi.org/project/filetype/#supported-types

and openpyxl uses Pillow to read images, these are the ones it supports: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html
</blockquote></details>

Seems to cover anything anyone might reasonably pass to this, and if not it will just fail. 
___
*[`src/code.sh` line 72 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/116#-N8xlo5x-FOQJC7mNyKF:-N90syk99PL8qpvuG1G6:b-nvdnxn) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/19b9bae4cf137adac1d2d9e3f774bca60b448692/src/code.sh#L72)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

hmmm so I wrote this to mimic the structure in app for array inputs and it looks like it doesn't sort by path by default (reading the docs I think it defaults to sorting by modified time on the files):
```
$ tree
.
└── in
    └── images
        ├── 0
        │   └── C.png
        ├── 1
        │   └── A.png
        ├── 2
        │   └── D.png
        └── 3
            └── B.png

$ images=$(find ./in/images/ -type f -name "*")
$ echo $images
./in/images/3/B.png ./in/images/0/C.png ./in/images/2/D.png ./in/images/1/A.png
```

if we pipe through `sort` life is good since DNAnexus has the incrementing integer in the path:
```
$ images=$(find ./in/images/ -type f -name "*" | sort)
$ echo $images
./in/images/0/C.png ./in/images/1/A.png ./in/images/2/D.png ./in/images/3/B.png
```

but in the job it sorts as we expect: https://platform.dnanexus.com/projects/GFFvFG042Zj7FxK74bpKVbjV/monitor/job/GFjY32842ZjPVQPG48zY6Jgq

rebuilt adding pipe through `sort` which is also in the order we expect and feels more robust and is correctly ordered: https://platform.dnanexus.com/projects/GFFvFG042Zj7FxK74bpKVbjV/monitor/job/GFjY9Bj42Zj7yj084XK1jgXk 


this was a good catch though, 10/10 reviewing :smile: 
</blockquote></details>

Nice, thanks for looking into it thoroughly


<!-- Sent from Reviewable.io -->

2022-08-09 09:18 UTC, merged