Decipher link
eastgenomics/eggd_generate_variant_workbook pull request #121
Opened 2022-08-15 14:54 UTC by kjwinfield

### Summary

**DECIPHER link**

DECIPHER is a database of rare disease variants ([https://www.deciphergenomics.org/](https://www.deciphergenomics.org/)). This update adds a link to the variant page in DECIPHER for variants reported in the workbooks. An extra column is added when the `--decipher` input is specified. This column is populated with links to the variant in DECIPHER. These links are only generated for build 38 variants, as DECIPHER only stores build 38 data

Example output:
![DECIPHER column with links added to spreadsheet](https://user-images.githubusercontent.com/71272357/184657880-6ad3610c-a64c-4da3-b76b-a23b8f8a6fbf.png)

**Tests**

Tests have been added to the tests.vcf file to test:
1. That the function to add a DECIPHER column works
2. That this column is only added when `--decipher` input is given
3. That the hyperlinks for the variants in DECIPHER are assembled correctly.
4. That the hyperlinks for variants in gnomAD ([https://gnomad.broadinstitute.org/](https://gnomad.broadinstitute.org/)) are correct, for both build 37 and build 38 variants.

### Unit tests

```
$ pytest
============================================================== test session starts ===============================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/katherine/eggd_generate_variant_workbook
collected 42 items                                                                                                                               

resources/home/dnanexus/generate_workbook/tests/test_columns.py ...........                                                           [ 26%]
resources/home/dnanexus/generate_workbook/tests/test_filters.py .......                                                                    [ 42%]
resources/home/dnanexus/generate_workbook/tests/test_utils.py ........                                                                     [ 61%]
resources/home/dnanexus/generate_workbook/tests/test_vcf.py ................                                                               [100%]

============================================================== 42 passed in 26.87s ===============================================================
```

2022-08-15 14:54 UTC, pep8speaks commented
Hello @kjwinfield! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`resources/home/dnanexus/generate_workbook/tests/test_vcf.py`](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py):

> [Line 278:1](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L278): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 291:9](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L291): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 292:9](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L292): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 294:1](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L294): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 315:9](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L315): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 316:9](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L316): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 318:1](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L318): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 322:35](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L322): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 323:34](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L323): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 324:42](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L324): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 335:1](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L335): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 339:77](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L339): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 343:9](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L343): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 344:9](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L344): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 350:35](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L350): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 351:34](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L351): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 352:43](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L352): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 360:80](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L360): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 362:14](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L362): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 363:1](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L363): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 367:67](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L367): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 372:53](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L372): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 373:13](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L373): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 374:56](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L374): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 375:13](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L375): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 377:1](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L377): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 379:22](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L379): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 391:18](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L391): [W291](https://duckd [...]

2022-08-15 16:33 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121)* status: 0 of 6 files reviewed, 16 unresolved discussions (waiting on @jethror1 and @kjwinfield)

___
*[`dxapp.json` line 207 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XAdHjCjUcIOBEPh4F:-N9XAdHk7QdZK300pdTT:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/dxapp.json#L207)):*
> ```JSON
>     {
>       "name": "decipher",
>       "label": "Determines hether or not to include column of DECIPHER links",
> ```

typo



_Code quote:_
```JSON
hether
```
___
*[`resources/home/dnanexus/generate_workbook/generate_workbook.py` line 246 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XAkdX968g5xcZ2yR0:-N9XAkdX968g5xcZ2yR1:bsapbp3) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/generate_workbook.py#L246)):*
> ```Python
>             help=(
>                 'Do you want a column of DECIPHER links included in the '
>                 'workbooks?'
> ```

since this isn't interactive it seems odd to word this as a question, can you just make this the same as the app input in dxapp.json 



_Code quote:_
```Python
                'Do you want a column of DECIPHER links included in the '
                'workbooks?'
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 283 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XAx2K9BYNOKWgjBwo:-N9XAx2K9BYNOKWgjBwp:b-3y4vaw) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L283)):*
> ```Python
>     '''
>     # @staticmethod is added to every function in this class so that self is
>     # not a required input
> ```

comment not really needed since you now know what static method does :)



_Code quote:_
```Python
    # @staticmethod is added to every function in this class so that self is
    # not a required input
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 291 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBIyY3gcs61xJQRkR:-N9XBIyY3gcs61xJQRkS:bq9oef5) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L291)):*
> ```Python
>         # Create test dataframe with no "DECIPHER" columnn
>         df = pd.DataFrame([
>         {'CHROM': 1, 'POS': 64883298, 'REF': 'T', 'ALT': 'C'},
> ```

pep8ness should have continuing lines indented to make it clear its continued from the previous line

https://peps.python.org/pep-0008/#indentation



_Code quote:_
```Python
        {'CHROM': 1, 'POS': 64883298, 'REF': 'T', 'ALT': 'C'},
        {'CHROM': 10, 'POS': 27035066, 'REF': 'C', 'ALT': 'T'},
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 294 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBXR965NYcnh5_E8z:-N9XBXR965NYcnh5_E9-:b-iyvhz2) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L294)):*
> ```Python
>         {'CHROM': 10, 'POS': 27035066, 'REF': 'C', 'ALT': 'T'},
>         ])
>         
> ```

whitespace



_Code quote:_
```Python
········
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 316 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBe6v-6rx99d_ut53:-N9XBe6v-6rx99d_ut54:b-gd0o86) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L316)):*
> ```Python
>         df = pd.DataFrame([
>         {'CHROM': 1, 'POS': 64883298, 'REF': 'T', 'ALT': 'C'},
>         {'CHROM': 10, 'POS': 27035066, 'REF': 'C', 'ALT': 'T'},
> ```

same as above about indentation



_Code quote:_
```Python
        {'CHROM': 1, 'POS': 64883298, 'REF': 'T', 'ALT': 'C'},
        {'CHROM': 10, 'POS': 27035066, 'REF': 'C', 'ALT': 'T'},
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 318 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBgKSA1JBJcPJi59G:-N9XBgKSA1JBJcPJi59H:b-iyvhz2) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L318)):*
> ```Python
>         {'CHROM': 10, 'POS': 27035066, 'REF': 'C', 'ALT': 'T'},
>         ])
>         
> ```

whitespace



_Code quote:_
```Python
·······
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 335 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBpqxD5mSjsP-Z6k2:-N9XBpqxD5mSjsP-Z6k3:bpy1gto) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L335)):*
> ```Python
>             'DECIPHER column not created despite --decipher input given'
>             )
>     
> ```

whitespace, this extension might help highlighting these (although the default Python linting should if you have it enabled): Name: Strict Whitespace
Id: sidp.strict-whitespace
Description: 
Version: 0.0.2
Publisher: Peter Simonsson
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=sidp.strict-whitespace



_Code quote:_
```Python
····
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 344 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XC4p14KZA9jlt4J52:-N9XC4p14KZA9jlt4J53:bsl0tdj) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L344)):*
> ```Python
>         df = pd.DataFrame([
>         {'CHROM': 1, 'POS': 64883298, 'REF': 'T', 'ALT': 'C'},
>         {'CHROM': 10, 'POS': 27035066, 'REF': 'C', 'ALT': 'T'},
> ```

indentation as above, won't comment the rest if there's more and let you sort them



_Code quote:_
```Python
        {'CHROM': 1, 'POS': 64883298, 'REF': 'T', 'ALT': 'C'},
        {'CHROM': 10, 'POS': 27035066, 'REF': 'C', 'ALT': 'T'},
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 407 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XCd1uA8xMwT2vcakp:-N9XCd1uA8xMwT2vcakq:b-s266lf) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L407)):*
> ```Python
>         test_vcf = vcf(argparse.Namespace(decipher=True))
>         test_vcf.vcfs=[df]
>         test_vcf.refs = ['38'] # Set reference = build 38
> ```

tiny thing but inline comments like this should have 2 spaces before the `#`



_Code quote:_
```Python
 # Set reference = build 38
```
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 443 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XCnvy5_USdkCIu19d:-N9XCnvz0OJ7tp7fJVRg:bynx48o) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L443)):*
> ```Python
>         valid_string = (
>         '=HYPERLINK("https://gnomad.broadinstitute.org/variant/1-1271940-C-T?d'
>         'ataset=gnomad_r2_1 [...]

2022-08-17 13:46 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121)* status: 0 of 6 files reviewed, 16 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_workbook/generate_workbook.py` line 246 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XAkdX968g5xcZ2yR0:-N9g1aDUA9oOpJ4QRqqb:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/generate_workbook.py#L246)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

since this isn't interactive it seems odd to word this as a question, can you just make this the same as the app input in dxapp.json 
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 283 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XAx2K9BYNOKWgjBwo:-N9fRRuSDKcrOhGz1EyJ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L283)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

comment not really needed since you now know what static method does :)
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 291 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBIyY3gcs61xJQRkR:-N9fRaeN7Ex9sPQ_7Az-:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L291)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

pep8ness should have continuing lines indented to make it clear its continued from the previous line

https://peps.python.org/pep-0008/#indentation
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 294 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBXR965NYcnh5_E8z:-N9fTPGvE9jdfwXvZWsM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L294)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 316 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBe6v-6rx99d_ut53:-N9fTQFt5DMqTMIoZDYs:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L316)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above about indentation
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 318 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBgKSA1JBJcPJi59G:-N9fTQ_YAytQh02-5Ar0:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L318)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whitespace
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 335 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XBpqxD5mSjsP-Z6k2:-N9fTRFn9XO0Igjm9AGa:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L335)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whitespace, this extension might help highlighting these (although the default Python linting should if you have it enabled): Name: Strict Whitespace
Id: sidp.strict-whitespace
Description: 
Version: 0.0.2
Publisher: Peter Simonsson
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=sidp.strict-whitespace
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 344 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XC4p14KZA9jlt4J52:-N9fTRph3KOMr9dm34xc:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L344)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

indentation as above, won't comment the rest if there's more and let you sort them
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 407 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XCd1uA8xMwT2vcakp:-N9fTXQz1kzDoR_ZUvtl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L407)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

tiny thing but inline comments like this should have 2 spaces before the `#`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 443 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XCnvy5_USdkCIu19d:-N9fTYdeC75ZmdnBQTFd:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L443)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

indentation for pep8 happiness as above
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/tests/test_vcf.py` line 470 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XCv-MEFBAUDB0idD9:-N9fTZPA6hnp4SOqn77h:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/tests/test_vcf.py#L470)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

indent
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 547 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XIOZGE3MPQKbLkgjv:-N9fTeNMAbh0ilF0qTCy:b-q072te) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/utils/vcf.py#L547)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not needed if a check for build is added to 
</blockquote></details>

Done. Have added filtering based on build to make_decipher_columns() function.
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 555 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121#-N9XDKlZES0tQzm9uTkp:-N9fTrL98xzXgtcQbpej:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/c74401086967b2448e785330c098a67981c971ae/resources/home/dnanexus/generate_workbook/utils/vcf.py#L555)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this is indented one tab too much
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_workbook/utils/vcf.py` line 562 at r1](https://reviewable. [...]

2022-08-17 14:03 UTC, jethror1 approved these changes
> Reviewed 1 of 6 files at r1, 2 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/121)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-08-17 14:03 UTC, merged